version: '3'

services:
  app:
    build: .
    container_name: calendarapp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development
  
  sidekiq:
    build: .
    container_name: calendar_sk
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq
    env_file:
      - .env

  redis:
    image: redis
    container_name: calendar_redis

  db:
    image: postgres
    container_name: calendarbd
    volumes:
      - db-volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: nopass

volumes:
  bundle-volume:
  db-volume:
  db-data:
    driver: local