version: '3'

services:
  app:
    build: .
    container_name: app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development

  db:
    image: postgres
    container_name: postgres_salareuniao
    volumes:
      - db-volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: nopass

volumes:
  bundle-volume:
  db-volume:
  db-data:
    driver: local