default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sala_de_reuniao_development
  host: db
  user: postgres
  password: nopass
  port: 5432

test:
  <<: *default
  database: sala_de_reuniao_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>